### ISSUE TITLE
支持一下最新API模型 或者能够手动自定义名字 方便下次更新

### ISSUE THREAD

**Issue by Joseph2Geek** [openai-translator/raycast-openai-translator#10]
如题。。。

**Comment by douo** [comment]
[Raycast Preferences](https://developers.raycast.com/api-reference/preferences) 不支持自定义，需要自己实现一套。如果模型变更频繁的话需要重新考虑下。

**Comment by douo** [comment]
已重新实现，现在支持自定义模型
![openai-translator 2024-03-26 at 23 13 33](https://github.com/openai-translator/raycast-openai-translator/assets/743074/77067be3-6fa1-469d-be18-0c4c8a171519)
