### ISSUE TITLE
能否支持Claude模型？

### ISSUE THREAD

**Issue by realCrush** [openai-translator/raycast-openai-translator#12]
根据评测，Claude 2模型能力介于GPT-3.5和GPT4之间，而且目前API免费，会是一个非常有竞争力模型，能否考虑支持此模型？

另外，我之前在Bob翻译软件中可以正常使用 [claude-to-chatgpt](https://github.com/jtsang4/claude-to-chatgpt) 插件将OpenAI请求转接到Claude，但似乎在您的插件里不能正常工作，返回的内容为空，请问这是为什么呢？（当然，最好是可以直接支持Claude模型啦）

- Raycast中的配置
![image](https://github.com/openai-translator/raycast-openai-translator/assets/57980447/d14cb9d2-f328-4cc9-8ee0-11e5a5070ac7)

- [claude-to-chatgpt](https://github.com/jtsang4/claude-to-chatgpt) 插件的log显示是有被正常调用的
![image](https://github.com/openai-translator/raycast-openai-translator/assets/57980447/6c2fae33-c239-4435-9671-0f5577e9e680)

- 但Raycast中返回的结果为空
![image](https://github.com/openai-translator/raycast-openai-translator/assets/57980447/a64f36af-e4f0-4d1d-a124-3440e4e3bff3)

**Comment by douo** [comment]
我没有使用 Claude API 的权限。已提交申请，通过后就来加上。

**Comment by douo** [comment]
> 根据评测，Claude 2模型能力介于GPT-3.5和GPT4之间，而且目前API免费，会是一个非常有竞争力模型，能否考虑支持此模型？
> 
> 另外，我之前在Bob翻译软件中可以正常使用 [claude-to-chatgpt](https://github.com/jtsang4/claude-to-chatgpt) 插件将OpenAI请求转接到Claude，但似乎在您的插件里不能正常工作，返回的内容为空，请问这是为什么呢？（当然，最好是可以直接支持Claude模型啦）
> 
> * Raycast中的配置
>   ![image](https://user-images.githubusercontent.com/57980447/257036985-d14cb9d2-f328-4cc9-8ee0-11e5a5070ac7.png)
> * [claude-to-chatgpt](https://github.com/jtsang4/claude-to-chatgpt) 插件的log显示是有被正常调用的
>   ![image](https://user-images.githubusercontent.com/57980447/257036864-6c2fae33-c239-4435-9671-0f5577e9e680.png)
> * 但Raycast中返回的结果为空
>   ![image](https://user-images.githubusercontent.com/57980447/257037003-a64f36af-e4f0-4d1d-a124-3440e4e3bff3.png)

模型名固定会不会影响返回结果？

**Comment by realCrush** [comment]
感谢回复，另外有个疑惑就是翻译界面右下角的矩形框能否隐藏？还是Raycast的框架不允许这样做？目前翻译原文+译文大约只占整个窗口约四分之一的空间，有点太局促了
![image](https://github.com/openai-translator/raycast-openai-translator/assets/57980447/b3de1a32-9617-4648-96e7-e56fb9a751b1)

**Comment by realCrush** [comment]
> > 根据评测，Claude 2模型能力介于GPT-3.5和GPT4之间，而且目前API免费，会是一个非常有竞争力模型，能否考虑支持此模型？
> > 另外，我之前在Bob翻译软件中可以正常使用 [claude-to-chatgpt](https://github.com/jtsang4/claude-to-chatgpt) 插件将OpenAI请求转接到Claude，但似乎在您的插件里不能正常工作，返回的内容为空，请问这是为什么呢？（当然，最好是可以直接支持Claude模型啦）
> > 
> > * Raycast中的配置
> >   ![image](https://user-images.githubusercontent.com/57980447/257036985-d14cb9d2-f328-4cc9-8ee0-11e5a5070ac7.png)
> > * [claude-to-chatgpt](https://github.com/jtsang4/claude-to-chatgpt) 插件的log显示是有被正常调用的
> >   ![image](https://user-images.githubusercontent.com/57980447/257036864-6c2fae33-c239-4435-9671-0f5577e9e680.png)
> > * 但Raycast中返回的结果为空
> >   ![image](https://user-images.githubusercontent.com/57980447/257037003-a64f36af-e4f0-4d1d-a124-3440e4e3bff3.png)
> 
> 模型名固定会不会影响返回结果？

我尝试了多个模型名，没有影响

**Comment by douo** [comment]
> 感谢回复，另外有个疑惑就是翻译界面右下角的矩形框能否隐藏？还是Raycast的框架不允许这样做？目前翻译原文+译文大约只占整个窗口约四分之一的空间，有点太局促了 ![image](https://user-images.githubusercontent.com/57980447/257419180-b3de1a32-9617-4648-96e7-e56fb9a751b1.png)

这个可以增加一个开关功能，方便独立提一个新 issue 吗？

**Comment by realCrush** [comment]
> > 感谢回复，另外有个疑惑就是翻译界面右下角的矩形框能否隐藏？还是Raycast的框架不允许这样做？目前翻译原文+译文大约只占整个窗口约四分之一的空间，有点太局促了 ![image](https://user-images.githubusercontent.com/57980447/257419180-b3de1a32-9617-4648-96e7-e56fb9a751b1.png)
> 
> 这个可以增加一个开关功能，方便独立提一个新 issue 吗？

好的，已为这个功能创建新的issue：https://github.com/openai-translator/raycast-openai-translator/issues/13

**Comment by douo** [comment]
已支持 Claude
![openai-translator 2024-03-26 at 23 12 45](https://github.com/openai-translator/raycast-openai-translator/assets/743074/94053f40-3453-4199-896f-9ece111f303b)
![openai-translator 2024-03-26 at 23 13 33](https://github.com/openai-translator/raycast-openai-translator/assets/743074/1705b67b-428a-4822-b879-9e21a5aeccd3)
