### ISSUE TITLE
界面右下角翻译器信息隐藏或替换成原文

### ISSUE THREAD

**Issue by realCrush** [openai-translator/raycast-openai-translator#13]
- 如图所示，目前翻译界面的原文+译文大约只占整个窗口约四分之一的空间，有点太局促了。翻译界面右下角的矩形框能否隐藏？大部分时候我不会想看现在使用的翻译器背后的模型是什么，可否设置个可选项让用户配置这一点

- 一个可能更好的选择是将右下角的翻译器信息换成展示原文，右上角展示译文，这样也方便对比

![](https://user-images.githubusercontent.com/57980447/257419180-b3de1a32-9617-4648-96e7-e56fb9a751b1.png)

**Comment by douo** [comment]
`⌘+ ^ + h` to toggle visiability of metadata in content view. You can also change the default visibility of metadata in extension preferences.

**Comment by realCrush** [comment]
> `⌘+ ^ + h` to toggle visiability of metadata in content view. You can also change the default visibility of metadata in extension preferences.

感谢，请问这些改动推送到Raycast Store的版本了吗？

**Comment by douo** [comment]
@realCrush 提交上去了，等审核：https://github.com/raycast/extensions/pull/8388
