### ISSUE TITLE
自定义 API url，但是没用

### ISSUE THREAD

**Issue by Lawrence-of-AnKing** [openai-translator/raycast-openai-translator#16]
我自定义了API URL，但是没用

![2023-10-11-101553](https://cdn.jsdelivr.net/gh/Lawrence-of-AnKing/ImgBank@main/imgMD/2023/10/2023-10-11-101553.png)

一直转圈，就是不出结果：

![2023-10-11-101456](https://cdn.jsdelivr.net/gh/Lawrence-of-AnKing/ImgBank@main/imgMD/2023/10/2023-10-11-101456.png)

但是在Chrome拓展上没问题 (https://github.com/openai-translator/openai-translator):

![2023-10-11-101015](https://cdn.jsdelivr.net/gh/Lawrence-of-AnKing/ImgBank@main/imgMD/2023/10/2023-10-11-101015.png)

是哪里设置错了吗？

**Comment by douo** [comment]
https://f2api.com/ 貌似没提供试用，无法测试。不过代码确实落后 https://github.com/openai-translator/openai-translator 很久，后面有空同步一下，再来验证。

**Comment by Lawrence-of-AnKing** [comment]
> https://f2api.com/ 貌似没提供试用，无法测试。不过代码确实落后 https://github.com/openai-translator/openai-translator 很久，后面有空同步一下，再来验证。

如果可以，希望能写一个GPT的插件，商店里那个似乎无法自定义API URL，反正也是无法用自己找的URL

**Comment by Lawrence-of-AnKing** [comment]
目前似乎仍然没有提供自定义API？我已经用chrome插件很久了，的确没有raycast方便。但是raycast插件又没有办法自定义API，作者有类似计划吗？

**Comment by douo** [comment]
![Screenshot 2024-01-25 at 10 45 12](https://github.com/openai-translator/raycast-openai-translator/assets/743074/4dcf3904-ff00-4d79-9c85-836e876dd484)

我一直是自定义 API 使用的，这个问题，我这边一直不能重现。不过这块逻辑最近有在重写，等更新再试试看。

**Comment by Lawrence-of-AnKing** [comment]
> ![Screenshot 2024-01-25 at 10 45 12](https://private-user-images.githubusercontent.com/743074/299520999-4dcf3904-ff00-4d79-9c85-836e876dd484.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYyNTM2MDAsIm5iZiI6MTcwNjI1MzMwMCwicGF0aCI6Ii83NDMwNzQvMjk5NTIwOTk5LTRkY2YzOTA0LWZmMDAtNGQ3OS05Yzg1LTgzNmU4NzZkZDQ4NC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTI2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEyNlQwNzE1MDBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03M2RkNzlmMmNkODI2OGEyMzU2MWJlZTAwMmVkZDRjODczNThhZjBmY2I0NmIyOGJlNGE2NGQ2NThlNGUyYjRjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.e-iZW3V6A98dykDNI0cIjOq0er1A6aki3DrDV1QoKqE)
> 
> 我一直是自定义 API 使用的，这个问题，我这边一直不能重现。不过这块逻辑最近有在重写，等更新再试试看。

找到原因了，在插件中有一个设置：

<img width="698" alt="image" src="https://github.com/openai-translator/raycast-openai-translator/assets/22313057/683262b1-3b29-4733-8fd0-7db9b7d14d9b">

通过将URL从 https://api.f2gpt.com 变成 https://api.f2gpt.com/v1/chat/completions ，成功翻译。
