### ISSUE TITLE
[Bug] 历史记录逻辑问题

### ISSUE THREAD

**Issue by realCrush** [openai-translator/raycast-openai-translator#18]
现有的历史记录存放满了以后，新进入的条目永远在堆栈顶部。
例如设置容量为30条，在容量满了以后最早的29条记录会一直存放，新进入的记录只会挤掉它的前一条记录，而合理的预期行为似乎应该是最新的记录挤掉最老的记录～

**Comment by douo** [comment]
稳定重现，应该是逻辑 BUG
