### ISSUE TITLE
希望提供 OpenAI 新的 GPT 4 Turbo 的支持

### ISSUE THREAD

**Issue by AeonWorks** [openai-translator/raycast-openai-translator#20]
虽然 Raycat 里有个 ChatGPT，但没有您开发的这个能够快捷调用方便。

能否考虑通过 https://api.openai.com/v1/models 这个接口自动检测可用的模型呢? 这样不用每次模型更新再做更新了。

据说 Raycat 里的 ChatGPT 插件就这么实现的。

供参考：

https://github.com/raycast/extensions/tree/563ab406f865a80608749bc3939c9f5ee566abee/extensions/chatgpt/

感谢开发此插件。

**Comment by douo** [comment]
感谢支持，模型已支持
![openai-translator 2024-03-26 at 23 13 33](https://github.com/openai-translator/raycast-openai-translator/assets/743074/9cc43c33-ebaf-483a-9375-ae12dfacf7e5)
