### ISSUE TITLE
选中文本后不会翻译

### ISSUE THREAD

**Issue by myeveryheart** [openai-translator/raycast-openai-translator#21]
首先感谢作者做了个这么棒的扩展。

我在safari中，先选择一段文本，然后使用快捷键调出翻译的界面，这个时候可以正常翻译的。
当我再次选择其他文本，继续用快捷键调出翻译的界面，大概率会出现翻译界面出来了，但它显示的还是上一次的界面，并没有把这次的文本显示出来。于是我esc退出界面，重新再来一次，又可以成功。

**Comment by myeveryheart** [comment]
补充：
按esc退出翻译界面，下次可以正常翻译新的内容。
点击界面外区域（也许只是隐藏了界面？），下次不翻译新的内容。

**Comment by douo** [comment]
感谢反馈🙏
测试了下，确实能复现。 应该是 raycast 的默认行为发生了改变。切换焦点（鼠标点击其他区域），只会导致 raycast 窗口隐藏，下次通过相同命令唤起，raycast 只是将窗口移到前台，并不会让窗口重绘。
OCR 没有这个问题，是因为 OCR 用 deeplink 唤起。回头我看看怎么解决。

**Comment by douo** [comment]
测试了下，raycast 窗口隐藏后，大概会缓存 20 秒。
