### ISSUE TITLE
希望能更新一下支持最新版本

### ISSUE THREAD

**Issue by androidcn** [openai-translator/raycast-openai-translator#22]

**Comment by douo** [comment]
收到，等手头的事少点就来安排。

**Comment by douo** [comment]
搞定了，重构了模型逻辑。
![openai-translator 2024-03-26 at 23 13 33](https://github.com/openai-translator/raycast-openai-translator/assets/743074/8597820b-6cef-42f8-ba28-9b6e4fb87b81)
