### ISSUE TITLE
希望提供 gpt-4o，或者用户自定义 model 的功能，这样以后 openai 更新了，就不需要发新版本了

### ISSUE THREAD

**Issue by suxiaoshao** [openai-translator/raycast-openai-translator#26]

**Comment by douo** [comment]
@suxiaoshao 最新版本已经支持自定义模型的：
![bc448176878a](https://github.com/openai-translator/raycast-openai-translator/assets/743074/c875b149-d44d-47fd-a491-bc448176878a)
