### ISSUE TITLE
gpt-4o-mini无法自定义

### ISSUE THREAD

**Issue by TeamBreakerr** [openai-translator/raycast-openai-translator#28]
提供的列表中没有gpt-4o-mini
再使用custom方法设定gpt-4o-mini之后进行保存，仍然会切换为默认的gpt-3.5-turbo-1106
<img width="621" alt="image" src="https://github.com/user-attachments/assets/759d0895-1523-4bc9-8246-036ce7fe882b">

**Comment by douo** [comment]
可复现

**Comment by douo** [comment]
最新版本已修复
